classificator: "sklearn.ensemble.ExtraTreesClassifier"
kwargs:
  - n_estimators: 100
  - max_depth: 3
  - min_samples_split: 2
  - min_samples_leaf: 1
  - max_features: "sqrt"
  - bootstrap: false
  - random_state: 42
  - warm_start: false