classificator: "sklearn.ensemble.GradientBoostingClassifier"
kwargs:
  - n_estimators: 100
  - learning_rate: 0.1
  - max_depth: 3
  - min_samples_split: 2
  - min_samples_leaf: 1
  - subsample: 1.0
  - random_state: 42
  - warm_start: false
  - validation_fraction: 0.1
  - n_iter_no_change: 10
