classificator: "sklearn.ensemble.HistGradientBoostingClassifier"
kwargs:
  - max_iter: 100
  - learning_rate: 0.1
  - max_depth: 3
  - min_samples_leaf: 20
  - max_bins: 255
  - l2_regularization: 0.0
  - early_stopping: true
  - random_state: 42