classificator: "sklearn.linear_model.LogisticRegression"
kwargs:
  - penalty: "l2"  
  - dual: false     
  - tol: 0.0001   
  - C: 1.0          
  - fit_intercept: true 
  - intercept_scaling: 1
  - solver: "lbfgs"  
  - max_iter: 100      
  - multi_class: "ovr"   
  - class_weight: null   
  