classificator: "sklearn.tree.DecisionTreeClassifier"
kwargs:
  - criterion: "gini"  
  - splitter: "best"   
  - max_depth: 5      
  - min_samples_split: 2 
  - min_samples_leaf: 1 
  - max_features: null 
  - max_leaf_nodes: null
  - class_weight: null  